//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkDynamicService.AlarmServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlarmServiceRef.IAlarmServiceOperations")]
    public interface IAlarmServiceOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/AddAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/AddAlarmResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.AlarmEventType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.Database.Alarm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.Database.Alarm[]))]
        bool AddAlarm(object alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/AddAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/AddAlarmResponse")]
        System.Threading.Tasks.Task<bool> AddAlarmAsync(object alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/DeleteAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/DeleteAlarmResponse")]
        bool DeleteAlarm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/DeleteAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/DeleteAlarmResponse")]
        System.Threading.Tasks.Task<bool> DeleteAlarmAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/AcknowledgeAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/AcknowledgeAlarmResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.AlarmEventType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.Database.Alarm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ScadaCommon.Database.Alarm[]))]
        bool AcknowledgeAlarm(object alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/AcknowledgeAlarm", ReplyAction="http://tempuri.org/IAlarmServiceOperations/AcknowledgeAlarmResponse")]
        System.Threading.Tasks.Task<bool> AcknowledgeAlarmAsync(object alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/GetAllAlarms", ReplyAction="http://tempuri.org/IAlarmServiceOperations/GetAllAlarmsResponse")]
        ScadaCommon.Database.Alarm[] GetAllAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmServiceOperations/GetAllAlarms", ReplyAction="http://tempuri.org/IAlarmServiceOperations/GetAllAlarmsResponse")]
        System.Threading.Tasks.Task<ScadaCommon.Database.Alarm[]> GetAllAlarmsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmServiceOperationsChannel : NetworkDynamicService.AlarmServiceRef.IAlarmServiceOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmServiceOperationsClient : System.ServiceModel.ClientBase<NetworkDynamicService.AlarmServiceRef.IAlarmServiceOperations>, NetworkDynamicService.AlarmServiceRef.IAlarmServiceOperations {
        
        public AlarmServiceOperationsClient() {
        }
        
        public AlarmServiceOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlarmServiceOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddAlarm(object alarm) {
            return base.Channel.AddAlarm(alarm);
        }
        
        public System.Threading.Tasks.Task<bool> AddAlarmAsync(object alarm) {
            return base.Channel.AddAlarmAsync(alarm);
        }
        
        public bool DeleteAlarm(int id) {
            return base.Channel.DeleteAlarm(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAlarmAsync(int id) {
            return base.Channel.DeleteAlarmAsync(id);
        }
        
        public bool AcknowledgeAlarm(object alarm) {
            return base.Channel.AcknowledgeAlarm(alarm);
        }
        
        public System.Threading.Tasks.Task<bool> AcknowledgeAlarmAsync(object alarm) {
            return base.Channel.AcknowledgeAlarmAsync(alarm);
        }
        
        public ScadaCommon.Database.Alarm[] GetAllAlarms() {
            return base.Channel.GetAllAlarms();
        }
        
        public System.Threading.Tasks.Task<ScadaCommon.Database.Alarm[]> GetAllAlarmsAsync() {
            return base.Channel.GetAllAlarmsAsync();
        }
    }
}
